# Generated by Django 4.0.4 on 2022-05-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('title2', models.CharField(max_length=80)),
                ('title3', models.CharField(max_length=80)),
                ('summary', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Media/main_img')),
            ],
        ),
    ]
