# Generated by Django 4.0.4 on 2022-05-22 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mahsulot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Media/categ_img')),
                ('izoh', models.TextField()),
                ('status', models.CharField(choices=[('True', 'Mavjud'), ('False', 'Mavjud emas')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sotuv', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Media/mah_img')),
                ('mah_nomi', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('True', 'Mavjud'), ('False', 'Mavjud emas')], max_length=20)),
                ('yangi_narx', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('eski_narx', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('kategoriya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahsulot.category')),
            ],
        ),
    ]
