# Generated by Django 4.0.4 on 2022-05-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsulot', '0002_category_mahsulot'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Media/brand_img')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
