# Generated by Django 4.0.4 on 2022-05-23 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahsulot', '0003_featuredbrand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedBrand',
        ),
    ]
