# Generated by Django 4.0.4 on 2022-05-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsulot', '0005_featuredbrand'),
    ]

    operations = [
        migrations.CreateModel(
            name='FromBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Media/blog_img')),
                ('status', models.CharField(choices=[('True', 'Mavjud'), ('False', 'Mavjud emas')], max_length=20)),
                ('slug', models.SlugField(max_length=20)),
                ('brand_name', models.CharField(max_length=50)),
                ('izoh', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('views', models.CharField(max_length=100)),
            ],
        ),
    ]
