# Generated by Django 4.0.4 on 2022-05-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsulot', '0007_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Belowfooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mah_nomi', models.CharField(max_length=80)),
                ('image', models.ImageField(upload_to='Media/mah_img')),
                ('yangi_narx', models.CharField(max_length=50)),
                ('eski_narx', models.CharField(max_length=50)),
            ],
        ),
    ]
