# Generated by Django 4.0.4 on 2022-05-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsulot', '0008_belowfooter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='Media/logo_img')),
                ('title', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=100)),
                ('hours', models.CharField(max_length=200)),
                ('follow', models.CharField(max_length=70)),
                ('fac_logo', models.TextField()),
                ('twit_logo', models.TextField()),
                ('ins_logo', models.TextField()),
                ('you_logo', models.TextField()),
            ],
        ),
    ]
