# Generated by Django 4.0.4 on 2022-05-27 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahsulot', '0010_appstore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appstore',
        ),
    ]
