# Generated by Django 4.0.4 on 2022-05-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsulot', '0012_appstore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutmain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='Media/about_img')),
            ],
        ),
    ]
