# Generated by Django 4.0.4 on 2022-05-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsulot', '0013_aboutmain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='Media/team_img')),
                ('name', models.CharField(max_length=50)),
                ('kasbi', models.CharField(max_length=100)),
                ('fac_logo', models.CharField(max_length=200)),
                ('twit_logo', models.CharField(max_length=200)),
                ('ins_logo', models.CharField(max_length=200)),
                ('you_logo', models.CharField(max_length=200)),
            ],
        ),
    ]
