# Generated by Django 4.0.4 on 2022-05-27 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahsulot', '0014_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
