# Generated by Django 4.0.4 on 2022-05-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsulot', '0017_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaraCorp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Media/pic_img')),
                ('place', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
    ]
