# Generated by Django 4.0.4 on 2022-05-29 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mahsulot', '0019_incontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('True', 'Mavjud'), ('False', 'Mavjud emas')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OurBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('True', 'Mavjud'), ('False', 'Mavjud emas')], max_length=20)),
                ('image', models.ImageField(upload_to='Media/ourblog_img')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('views', models.CharField(max_length=100)),
                ('kategoriy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahsulot.categoryblog')),
            ],
        ),
    ]
